name: Deploy to Heroku

on:
  workflow_dispatch:
    inputs:
      heroku_api_key:
        description: 'Heroku API Key'
        required: true
      heroku_app_name:
        description: 'Heroku App Name'
        required: true
      heroku_email:
        description: 'Heroku Email'
        required: true
      heroku_team_name:
        description: 'Heroku Team Name'
        required: true

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ github.event.inputs.heroku_api_key }}
        heroku_app_name: ${{ github.event.inputs.heroku_app_name }}
        heroku_email: ${{ github.event.inputs.heroku_email }}
        usedocker: false
        app_name: ${{ github.event.inputs.heroku_app_name }}
        team: ${{ github.event.inputs.heroku_team_name }}
